// This file is used to define how the project is build in Jenkins
// See the syntax at https://jenkins.io/doc/book/pipeline/syntax/

pipeline {
    agent any

    options {
        // Prepend all console output generated by the Pipeline run with the time at which the line was emitted
        timestamps()
    }

    stages {
        stage('Build') {
            steps {
                sh 'make build-in-docker'
            }
        }
        stage('Test') {
            steps {
                echo 'Testing..'
            }
        }
    }
}